export const stateKeywords: { [key: string]: string[] } = {
    Alabama: ['Alabama', 'Birmingham', 'Montgomery', 'AL'],
    Alaska: ['Alaska', 'Anchorage', 'Juneau', 'AK'],
    Arizona: ['Arizona', 'Phoenix', 'Tucson', 'AZ'],
    Arkansas: ['Arkansas', 'Little Rock', 'Fayetteville', 'AR'],
    California: ['California', 'Los Angeles', 'San Francisco', 'San Diego', 'CA'],
    Colorado: ['Colorado', 'Denver', 'Boulder', 'CO'],
    Connecticut: ['Connecticut', 'Hartford', 'New Haven', 'CT'],
    Delaware: ['Delaware', 'Wilmington', 'Dover', 'DE'],
    Florida: ['Florida', 'Miami', 'Orlando', 'Tampa', 'FL'],
    Georgia: ['Georgia', 'Atlanta', 'Savannah', 'GA'],
    Hawaii: ['Hawaii', 'Honolulu', 'Maui', 'HI'],
    Idaho: ['Idaho', 'Boise', 'Idaho Falls', 'ID'],
    Illinois: ['Illinois', 'Chicago', 'Springfield', 'IL'],
    Indiana: ['Indiana', 'Indianapolis', 'Fort Wayne', 'IN'],
    Iowa: ['Iowa', 'Des Moines', 'Cedar Rapids', 'IA'],
    Kansas: ['Kansas', 'Wichita', 'Topeka', 'KS'],
    Kentucky: ['Kentucky', 'Louisville', 'Lexington', 'KY'],
    Louisiana: ['Louisiana', 'New Orleans', 'Baton Rouge', 'LA'],
    Maine: ['Maine', 'Portland', 'Augusta', 'ME'],
    Maryland: ['Maryland', 'Baltimore', 'Annapolis', 'MD'],
    Massachusetts: ['Massachusetts', 'Boston', 'Cambridge', 'MA'],
    Michigan: ['Michigan', 'Detroit', 'Grand Rapids', 'MI'],
    Minnesota: ['Minnesota', 'Minneapolis', 'Saint Paul', 'MN'],
    Mississippi: ['Mississippi', 'Jackson', 'Biloxi', 'MS'],
    Missouri: ['Missouri', 'Kansas City', 'St. Louis', 'MO'],
    Montana: ['Montana', 'Billings', 'Missoula', 'MT'],
    Nebraska: ['Nebraska', 'Omaha', 'Lincoln', 'NE'],
    Nevada: ['Nevada', 'Las Vegas', 'Reno', 'NV'],
    "New Hampshire": ['New Hampshire', 'Concord', 'Manchester', 'NH'],
    "New Jersey": ['New Jersey', 'Newark', 'Trenton', 'NJ'],
    "New Mexico": ['New Mexico', 'Albuquerque', 'Santa Fe', 'NM'],
    "New York": ['New York', 'NYC', 'Buffalo', 'Albany', 'NY'],
    "North Carolina": ['North Carolina', 'Charlotte', 'Raleigh', 'NC'],
    "North Dakota": ['North Dakota', 'Fargo', 'Bismarck', 'ND'],
    Ohio: ['Ohio', 'Cleveland', 'Columbus', 'OH'],
    Oklahoma: ['Oklahoma', 'Oklahoma City', 'Tulsa', 'OK'],
    Oregon: ['Oregon', 'Portland', 'Salem', 'OR'],
    Pennsylvania: ['Pennsylvania', 'Philadelphia', 'Pittsburgh', 'PA'],
    "Rhode Island": ['Rhode Island', 'Providence', 'Newport', 'RI'],
    "South Carolina": ['South Carolina', 'Charleston', 'Columbia', 'SC'],
    "South Dakota": ['South Dakota', 'Sioux Falls', 'Pierre', 'SD'],
    Tennessee: ['Tennessee', 'Nashville', 'Memphis', 'TN'],
    Texas: ['Texas', 'Houston', 'Dallas', 'Austin', 'TX'],
    Utah: ['Utah', 'Salt Lake City', 'Provo', 'UT'],
    Vermont: ['Vermont', 'Montpelier', 'Burlington', 'VT'],
    Virginia: ['Virginia', 'Richmond', 'Virginia Beach', 'VA'],
    Washington: ['Washington', 'Seattle', 'Spokane', 'WA'],
    "West Virginia": ['West Virginia', 'Charleston', 'Morgantown', 'WV'],
    Wisconsin: ['Wisconsin', 'Milwaukee', 'Madison', 'WI'],
    Wyoming: ['Wyoming', 'Cheyenne', 'Casper', 'WY'],
    "District of Columbia": ['Washington, D.C.', 'DC', 'District of Columbia'],
  };
  